name: Specific File Deploy

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/index.html'  # Only deploys when the index.html file in the docs folder is altered

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload the website files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4